### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by shaneu** [jsdevel/bash-bootstrap#3]
First of all, awesome job with this! Thanks so much for putting it out there!

When I tried to run `./setup.bash`, I was getting the following error 

```
./setup.bash: line 17: /setup-scripts/bash: No such file or directory
./setup.bash: line 17: /setup-scripts/git: No such file or directory
./setup.bash: line 17: /setup-scripts/vim: No such file or directory
```

so in setup.bash i added 
```
 function setup(){
-  . $SETUP_SCRIPTS_DIR/$1
+  . ./$SETUP_SCRIPTS_DIR/$1
 }
```
That made it work. I also had to install cmake, once I did that everything installed! 

Thanks again brother

**Comment by jsdevel** [comment]
hey, thanks!  I'll update it.

**Comment by jsdevel** [comment]
closed by https://github.com/jsdevel/bash-bootstrap/commit/4e6163bd9b94fabcbc4c5d8afd0e727956f7901b
